#!/bin/bash

FBX_LON=-147.7164
FBX_LAT=64.8378

SCALE_LON=-140
SCALE_LAT=53

gmt set FONT 12p

gmt begin alaska png
  gmt grdimage @earth_relief_01m -I -R171/231/50/73 -Cgeo -JS201/90/8i -Baf
  echo $FBX_LON $FBX_LAT | gmt plot -Sc0.25c -Gblack
  echo $FBX_LON $FBX_LAT Fairbanks | gmt text -F+jLM -D0.25c/0
  gmt coast -N1/0.5p,black -W0.5p -A0/0/1
  gmt basemap -Lg$SCALE_LON/$SCALE_LAT+c$SCALE_LON/$SCALE_LAT+w500+f+l
gmt end

rm gmt.conf
